apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  replicas: {{ .Values.pushgateway.replicas }}
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
{{- if .Values.pushgateway.tolerations }}
      tolerations:
{{ toYaml .Values.pushgateway.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: pushgateway
        image: {{ .Values.pushgateway.image }}
        ports:
          - name: http
            containerPort: 9091